In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px

In [2]:
df = pd.read_csv('data_comexstat.csv', encoding='cp1252')

In [3]:
df

              date product state  ...   route       tons         usd
0       1997-01-01    corn    ES  ...     Sea     44.045    113029.0
1       1997-01-01    corn    GO  ...  Ground     54.000     36720.0
2       1997-01-01    corn    GO  ...  Ground      0.200       180.0
3       1997-01-01    corn    GO  ...     Sea      3.488      5688.0
4       1997-01-01    corn    MG  ...  Ground     27.000     18630.0
...            ...     ...   ...  ...     ...        ...         ...
117960  2019-12-01   wheat    SP  ...     Sea  87124.765  17897516.0
117961  2019-12-01   wheat    SP  ...     Sea      0.500       477.0
117962  2019-12-01   wheat    SP  ...     Sea      5.769      6726.0
117963  2019-12-01   wheat    SP  ...   Other      0.025        50.0
117964  2019-12-01   wheat    SP  ...   Other      0.010        85.0

[117965 rows x 8 columns]

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
expt = df.loc[df['type']=='Export']

In [6]:
expt

             date product state  ...   route        tons         usd
2      1997-01-01    corn    GO  ...  Ground       0.200       180.0
3      1997-01-01    corn    GO  ...     Sea       3.488      5688.0
5      1997-01-01    corn    MS  ...  Ground      40.000     38700.0
9      1997-01-01    corn    PR  ...     Sea  170000.000  20000000.0
10     1997-01-01    corn    PR  ...  Ground     258.300    386733.0
...           ...     ...   ...  ...     ...         ...         ...
117952 2019-12-01   wheat    PR  ...     Sea       0.400       400.0
117957 2019-12-01   wheat    RS  ...     Sea   36698.000   6963002.0
117961 2019-12-01   wheat    SP  ...     Sea       0.500       477.0
117963 2019-12-01   wheat    SP  ...   Other       0.025        50.0
117964 2019-12-01   wheat    SP  ...   Other       0.010        85.0

[105861 rows x 8 columns]

In [7]:
expt.groupby(by='product').size()

product
corn            17394
soybean_meal    17672
soybean_oil     15287
soybeans        21817
sugar           32988
wheat             703
dtype: int64

In [8]:
soybeans = expt.loc[expt['product']=='soybeans']
soybeans

             date   product state  ...   route       tons         usd
73     1997-01-01  soybeans    GO  ...     Sea  13730.000   3954240.0
74     1997-01-01  soybeans    MT  ...   Other    100.000     60500.0
75     1997-01-01  soybeans    RS  ...  Ground    200.000    104000.0
167    1997-02-01  soybeans    GO  ...     Sea   3000.000    855450.0
168    1997-02-01  soybeans    MT  ...     Sea   5000.000   1436185.0
...           ...       ...   ...  ...     ...        ...         ...
117584 2019-12-01  soybeans    SP  ...   Other      0.004        11.0
117585 2019-12-01  soybeans    SP  ...   Other      0.006        30.0
117586 2019-12-01  soybeans    SP  ...     Sea    146.499     52813.0
117587 2019-12-01  soybeans    TO  ...     Sea  63731.482  22986541.0
117588 2019-12-01  soybeans    TO  ...     Sea   4068.461   1418269.0

[21817 rows x 8 columns]

In [9]:
soyoil = expt.loc[expt['product']=='soybean_oil']
soyoil

             date      product state  ...   route      tons        usd
57     1997-01-01  soybean_oil    MS  ...   Other    48.053    43268.0
58     1997-01-01  soybean_oil    MT  ...     Sea  6000.000  3002191.0
61     1997-01-01  soybean_oil    PR  ...     Sea  5430.000  2920399.0
62     1997-01-01  soybean_oil    PR  ...     Sea  8095.000  4129840.0
63     1997-01-01  soybean_oil    PR  ...     Sea   500.000   287150.0
...           ...          ...   ...  ...     ...       ...        ...
117499 2019-12-01  soybean_oil    SP  ...  Ground     4.004    12212.0
117500 2019-12-01  soybean_oil    SP  ...   Other     0.154      278.0
117501 2019-12-01  soybean_oil    SP  ...   Other     0.020       14.0
117502 2019-12-01  soybean_oil    SP  ...   Other     0.180      208.0
117503 2019-12-01  soybean_oil    SP  ...     Sea  1414.694  1519688.0

[15287 rows x 8 columns]

In [10]:
soymeal = expt.loc[expt['product']=='soybean_meal']
soymeal

             date       product state  ... route       tons        usd
19     1997-01-01  soybean_meal    GO  ...   Sea    419.070   119318.0
20     1997-01-01  soybean_meal    GO  ...   Sea   5000.000  1414250.0
21     1997-01-01  soybean_meal    MS  ...   Sea    140.672    38378.0
22     1997-01-01  soybean_meal    MS  ...   Sea  15000.000  4042100.0
23     1997-01-01  soybean_meal    MS  ...   Sea  14000.000  3850162.0
...           ...           ...   ...  ...   ...        ...        ...
117367 2019-12-01  soybean_meal    SP  ...   Sea   2259.887   800000.0
117368 2019-12-01  soybean_meal    SP  ...   Sea  17300.000  5803448.0
117369 2019-12-01  soybean_meal    TO  ...   Sea   1537.455   466218.0
117370 2019-12-01  soybean_meal    TO  ...   Sea   2933.194   889462.0
117371 2019-12-01  soybean_meal    TO  ...   Sea    835.333   288457.0

[17672 rows x 8 columns]

In [11]:
expt.groupby(by='state').size()

state
AC       70
AL     1073
AM      215
AP       24
BA     1730
CE       94
DF      516
ES      772
GO    10693
MA     1150
MG     7632
MS     6999
MT    16728
PA     1063
PB      289
PE     1174
PI      523
PR    14930
RJ      583
RN      139
RO     1167
RR      328
RS     6921
SC     4198
SE      174
SP    25652
TO     1024
dtype: int64

**Questão 01**

In [12]:
evsoybean = soybeans.groupby(['date','state'])['usd'].sum()
evsoybean

date        state
1997-01-01  GO         3954240.0
            MT           60500.0
            RS          104000.0
1997-02-01  GO          855450.0
            MT         1436185.0
                        ...
2019-12-01  RR         8313197.0
            RS       310457437.0
            SC        38695345.0
            SP        14869722.0
            TO        24404810.0
Name: usd, Length: 3345, dtype: float64

In [13]:
tsoybean = soybeans.groupby(by='date')['usd'].sum()
tsoybean

date
1997-01-01    4.118740e+06
1997-02-01    4.896148e+06
1997-03-01    1.562010e+08
1997-04-01    4.600374e+08
1997-05-01    4.872645e+08
                  ...
2019-08-01    1.628516e+09
2019-09-01    1.562372e+09
2019-10-01    1.704494e+09
2019-11-01    1.625917e+09
2019-12-01    1.061904e+09
Name: usd, Length: 276, dtype: float64

In [14]:
evsoyoil = soyoil.groupby(['date','state'])['usd'].sum()
evsoyoil

date        state
1997-01-01  MS          43268.0
            MT        3002191.0
            PR       12178843.0
            RS       19492775.0
1997-02-01  PR        6185693.0
                        ...
2019-12-01  RJ            513.0
            RR        1537383.0
            RS         662531.0
            SC        1917179.0
            SP        1559347.0
Name: usd, Length: 2367, dtype: float64

In [15]:
tsoyoil = soyoil.groupby(by='date')['usd'].sum()
tsoyoil

date
1997-01-01    34717077.0
1997-02-01    18351677.0
1997-03-01    11659979.0
1997-04-01    84030219.0
1997-05-01    81412001.0
                 ...
2019-08-01    71356388.0
2019-09-01    53719755.0
2019-10-01    45519774.0
2019-11-01    17694618.0
2019-12-01    29863391.0
Name: usd, Length: 276, dtype: float64

In [16]:
evsoymeal = soymeal.groupby(['date','state'])['usd'].sum()
evsoymeal

date        state
1997-01-01  GO        1533568.0
            MS        7930640.0
            MT        8274666.0
            PR       54485462.0
            RS       36154190.0
                        ...
2019-12-01  PR       54836292.0
            RS       92878306.0
            SC       10418384.0
            SP       18284629.0
            TO        1644137.0
Name: usd, Length: 2444, dtype: float64

In [17]:
tsoymeal = soymeal.groupby(by='date')['usd'].sum()
tsoymeal

date
1997-01-01    133239012.0
1997-02-01     47590539.0
1997-03-01    152682096.0
1997-04-01    324619851.0
1997-05-01    344844289.0
                 ...
2019-08-01    471881167.0
2019-09-01    444065384.0
2019-10-01    476875165.0
2019-11-01    413252025.0
2019-12-01    543725029.0
Name: usd, Length: 276, dtype: float64

In [18]:
tbean = pd.DataFrame(tsoybean)
tbean.reset_index(inplace=True)
tbean.columns = ['Data', 'Total (USD)']
tbean

          Data   Total (USD)
0   1997-01-01  4.118740e+06
1   1997-02-01  4.896148e+06
2   1997-03-01  1.562010e+08
3   1997-04-01  4.600374e+08
4   1997-05-01  4.872645e+08
..         ...           ...
271 2019-08-01  1.628516e+09
272 2019-09-01  1.562372e+09
273 2019-10-01  1.704494e+09
274 2019-11-01  1.625917e+09
275 2019-12-01  1.061904e+09

[276 rows x 2 columns]

**Nos gráficos abaixo têm-se o total de vendas (em dólares americanos) com a exportação de soja em grãos, óleo de soja e carne de soja.**

In [19]:
fig = px.line(tbean, x='Data', y='Total (USD)', title='Evolução do total de exportação de soja em grãos')
fig.update_xaxes(rangeslider_visible=True)
fig.show()

In [77]:
toil = pd.DataFrame(tsoyoil)
toil.reset_index(inplace=True)
toil.columns = ['Data', 'Total (USD)']

In [21]:
fig = px.line(toil, x='Data', y='Total (USD)', title='Evolução do total de exportação de óleo de soja')
fig.update_xaxes(rangeslider_visible=True)
fig.show()

In [78]:
tmeal = pd.DataFrame(tsoymeal)
tmeal.reset_index(inplace=True)
tmeal.columns = ['Data', 'Total (USD)']

In [23]:
fig = px.line(toil, x='Data', y='Total (USD)', title='Evolução do total de exportação de carne de soja')
fig.update_xaxes(rangeslider_visible=True)
fig.show()

**Questão 02**

In [24]:
expt.groupby(by='product').size()

product
corn            17394
soybean_meal    17672
soybean_oil     15287
soybeans        21817
sugar           32988
wheat             703
dtype: int64

In [25]:
crn = expt.loc[df['product']=='corn']
crn

             date product state  ...   route        tons         usd
2      1997-01-01    corn    GO  ...  Ground       0.200       180.0
3      1997-01-01    corn    GO  ...     Sea       3.488      5688.0
5      1997-01-01    corn    MS  ...  Ground      40.000     38700.0
9      1997-01-01    corn    PR  ...     Sea  170000.000  20000000.0
10     1997-01-01    corn    PR  ...  Ground     258.300    386733.0
...           ...     ...   ...  ...     ...         ...         ...
117265 2019-12-01    corn    SP  ...     Sea    2575.793    402284.0
117266 2019-12-01    corn    TO  ...     Sea   27908.815   4433950.0
117267 2019-12-01    corn    TO  ...     Sea    1293.930    229003.0
117268 2019-12-01    corn    TO  ...     Air       0.007        27.0
117269 2019-12-01    corn    TO  ...     Sea    1874.085    283988.0

[17394 rows x 8 columns]

In [26]:
crn5 = (crn['date'] >= '2014-12-01') & (crn['date'] <= '2019-12-01')
tcrn = crn[crn5]
tcrn

             date product state  ... route       tons        usd
75015  2014-12-01    corn    BA  ...   Sea  22585.893  4133218.0
75016  2014-12-01    corn    DF  ...   Sea      1.403      247.0
75017  2014-12-01    corn    GO  ...   Sea  31271.840  5868054.0
75019  2014-12-01    corn    GO  ...   Sea      3.600      648.0
75020  2014-12-01    corn    GO  ...   Sea     21.890    56796.0
...           ...     ...   ...  ...   ...        ...        ...
117265 2019-12-01    corn    SP  ...   Sea   2575.793   402284.0
117266 2019-12-01    corn    TO  ...   Sea  27908.815  4433950.0
117267 2019-12-01    corn    TO  ...   Sea   1293.930   229003.0
117268 2019-12-01    corn    TO  ...   Air      0.007       27.0
117269 2019-12-01    corn    TO  ...   Sea   1874.085   283988.0

[7819 rows x 8 columns]

Valor total de exportação de milho nos últimos 5 anos.

In [27]:
crnt = tcrn['usd'].sum()
crnt

25075409650.0

In [28]:
sgr = expt.loc[df['product']=='sugar']
sgr

             date product state  ...   route       tons        usd
76     1997-01-01   sugar    PE  ...     Air   1000.000   307000.0
77     1997-01-01   sugar    PE  ...     Sea  12400.000  3587650.0
78     1997-01-01   sugar    PE  ...     Sea   3560.000  1032400.0
79     1997-01-01   sugar    PE  ...     Sea   9040.000  2798359.0
80     1997-01-01   sugar    PE  ...     Sea  28000.000  8190000.0
...           ...     ...   ...  ...     ...        ...        ...
117919 2019-12-01   sugar    SP  ...  Ground   1890.000   577618.0
117920 2019-12-01   sugar    SP  ...  Ground     80.000    55491.0
117921 2019-12-01   sugar    SP  ...     Sea   8967.646  3828624.0
117922 2019-12-01   sugar    SP  ...     Sea   5805.000  1726058.0
117923 2019-12-01   sugar    SP  ...     Sea  21422.839  6066211.0

[32988 rows x 8 columns]

In [29]:
sgr5 = (sgr['date'] >= '2014-12-01') & (sgr['date'] <= '2019-12-01')
tsgr = sgr[sgr5]
tsgr

             date product state  ...   route       tons        usd
75286  2014-12-01   sugar    AC  ...  Ground     74.955    45172.0
75287  2014-12-01   sugar    AL  ...     Sea   1890.000   830499.0
75288  2014-12-01   sugar    AL  ...     Sea    270.000   118643.0
75289  2014-12-01   sugar    AL  ...     Sea  27000.000  9149587.0
75290  2014-12-01   sugar    AL  ...     Sea   1026.000   450842.0
...           ...     ...   ...  ...     ...        ...        ...
117919 2019-12-01   sugar    SP  ...  Ground   1890.000   577618.0
117920 2019-12-01   sugar    SP  ...  Ground     80.000    55491.0
117921 2019-12-01   sugar    SP  ...     Sea   8967.646  3828624.0
117922 2019-12-01   sugar    SP  ...     Sea   5805.000  1726058.0
117923 2019-12-01   sugar    SP  ...     Sea  21422.839  6066211.0

[13790 rows x 8 columns]

Valor total de exportação de açúcar nos últimos 5 anos.

In [30]:
sgrt = tsgr['usd'].sum()
sgrt

41756192906.0

In [31]:
wh = expt.loc[df['product']=='wheat']
wh

             date product state  ...  route       tons        usd
17466  2003-12-01   wheat    MG  ...    Sea      1.500      657.0
17711  2004-01-01   wheat    MG  ...    Sea      3.000     1269.0
21208  2005-01-01   wheat    MG  ...    Sea      0.400      164.0
21780  2005-03-01   wheat    MG  ...    Sea      0.400      170.0
22459  2005-05-01   wheat    PR  ...    Sea      0.390      231.0
...           ...     ...   ...  ...    ...        ...        ...
117952 2019-12-01   wheat    PR  ...    Sea      0.400      400.0
117957 2019-12-01   wheat    RS  ...    Sea  36698.000  6963002.0
117961 2019-12-01   wheat    SP  ...    Sea      0.500      477.0
117963 2019-12-01   wheat    SP  ...  Other      0.025       50.0
117964 2019-12-01   wheat    SP  ...  Other      0.010       85.0

[703 rows x 8 columns]

In [32]:
wh5 = (wh['date'] >= '2014-12-01') & (wh['date'] <= '2019-12-01')
twh = wh[wh5]
twh

             date product state  ...  route       tons        usd
75484  2014-12-01   wheat    PR  ...  Other      0.001        1.0
75485  2014-12-01   wheat    PR  ...    Air      0.025       25.0
75486  2014-12-01   wheat    PR  ...  Other      0.200      251.0
75490  2014-12-01   wheat    PR  ...    Sea      1.100     1704.0
75491  2014-12-01   wheat    PR  ...    Sea    498.720    90767.0
...           ...     ...   ...  ...    ...        ...        ...
117952 2019-12-01   wheat    PR  ...    Sea      0.400      400.0
117957 2019-12-01   wheat    RS  ...    Sea  36698.000  6963002.0
117961 2019-12-01   wheat    SP  ...    Sea      0.500      477.0
117963 2019-12-01   wheat    SP  ...  Other      0.025       50.0
117964 2019-12-01   wheat    SP  ...  Other      0.010       85.0

[378 rows x 8 columns]

Valor total de exportação de trigo nos últimos 5 anos.

In [33]:
wht = twh['usd'].sum()
wht

795773189.0

In [34]:
sb5 = (soybeans['date'] >= '2014-12-01') & (soybeans['date'] <= '2019-12-01')
tsb = soybeans[sb5]
tsb

             date   product state  ...  route       tons         usd
75268  2014-12-01  soybeans    GO  ...    Sea   1823.389    979160.0
75269  2014-12-01  soybeans    MG  ...    Air      0.400       188.0
75271  2014-12-01  soybeans    MT  ...    Sea   4600.000   2615744.0
75272  2014-12-01  soybeans    MT  ...    Sea  29502.101  15842628.0
75273  2014-12-01  soybeans    PR  ...    Sea     15.330     17321.0
...           ...       ...   ...  ...    ...        ...         ...
117584 2019-12-01  soybeans    SP  ...  Other      0.004        11.0
117585 2019-12-01  soybeans    SP  ...  Other      0.006        30.0
117586 2019-12-01  soybeans    SP  ...    Sea    146.499     52813.0
117587 2019-12-01  soybeans    TO  ...    Sea  63731.482  22986541.0
117588 2019-12-01  soybeans    TO  ...    Sea   4068.461   1418269.0

[7191 rows x 8 columns]

Valor total de exportação de grãos de soja nos últimos 5 anos.

In [35]:
sbt = tsb['usd'].sum()
sbt

123399102781.0

In [36]:
so5 = (soyoil['date'] >= '2014-12-01') & (soyoil['date'] <= '2019-12-01')
tso = soyoil[so5]
tso

             date      product state  ...   route      tons        usd
75225  2014-12-01  soybean_oil    GO  ...     Sea    23.198    28315.0
75226  2014-12-01  soybean_oil    GO  ...     Sea     6.959     7510.0
75227  2014-12-01  soybean_oil    GO  ...     Sea   479.503   461687.0
75228  2014-12-01  soybean_oil    GO  ...     Sea    74.565    80778.0
75229  2014-12-01  soybean_oil    GO  ...     Sea    24.855    27913.0
...           ...          ...   ...  ...     ...       ...        ...
117499 2019-12-01  soybean_oil    SP  ...  Ground     4.004    12212.0
117500 2019-12-01  soybean_oil    SP  ...   Other     0.154      278.0
117501 2019-12-01  soybean_oil    SP  ...   Other     0.020       14.0
117502 2019-12-01  soybean_oil    SP  ...   Other     0.180      208.0
117503 2019-12-01  soybean_oil    SP  ...     Sea  1414.694  1519688.0

[4590 rows x 8 columns]

Valor total de exportação de óleo de soja nos últimos 5 anos.

In [37]:
sot = tso['usd'].sum()
sot

4860602161.0

In [38]:
sm5 = (soymeal['date'] >= '2014-12-01') & (soymeal['date'] <= '2019-12-01')
tsm = soymeal[sm5]
tsm

             date       product state  ... route       tons         usd
75167  2014-12-01  soybean_meal    BA  ...   Sea  64686.602  30476218.0
75168  2014-12-01  soybean_meal    BA  ...   Sea  32997.226  14192015.0
75169  2014-12-01  soybean_meal    GO  ...   Sea    309.815    134770.0
75170  2014-12-01  soybean_meal    GO  ...   Sea   1343.500   1276325.0
75171  2014-12-01  soybean_meal    GO  ...   Sea   1004.350    465471.0
...           ...           ...   ...  ...   ...        ...         ...
117367 2019-12-01  soybean_meal    SP  ...   Sea   2259.887    800000.0
117368 2019-12-01  soybean_meal    SP  ...   Sea  17300.000   5803448.0
117369 2019-12-01  soybean_meal    TO  ...   Sea   1537.455    466218.0
117370 2019-12-01  soybean_meal    TO  ...   Sea   2933.194    889462.0
117371 2019-12-01  soybean_meal    TO  ...   Sea    835.333    288457.0

[5210 rows x 8 columns]

Valor total de exportação de carne de soja nos últimos 5 anos.

In [39]:
smt = tsm['usd'].sum()
smt

28815893103.0

In [40]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["Milho", "Açúcar", "Trigo", "Grãos de soja", "Óleo de soja", "Carne de soja"],
    y=[crnt, sgrt, wht, sbt, sot, smt]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=750,
    yaxis=dict(
        title_text="Total de exportações nos últimos 5 anos (USD)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

**Resposta**

Pelo gráfico acima percebe-se que os principais produtos exportados nos últimos 5 anos pelo Brasil são: Grão de soja, açúcar e carne de soja.

**Questão 03**

In [41]:
rt = tcrn.groupby(by='route').size()
rt

route
Air        385
Ground     498
Other      464
River      296
Sea       6176
dtype: int64

In [42]:
labels = ['Aérea','Terrestre','Rios','Marítima','Outros']
values = [385, 498, 296, 6176, 464]

fig = go.Figure(data=[go.Pie(labels=labels, values=values)])
fig.update_layout(title_text="Principais tipos de rotas de exportação de milho nos últimos 5 anos")
fig.show()

**Resposta**

Pelo gráfico acima é possível observar que nos últimos 5 anos as principais rotas de exportação de milho foram do tipo marítima e terrestre. Tal predominância pela via marítima se deve ao fato de a maior parte dos mercados importadores estarem situados em outros continentes, daí a escolha pela rota marítima. A escolha do tipo de rota adequada é de vital importância devido a sua influência no custo final de venda.

**Questão 04**

In [43]:
crn3 = (crn['date'] >= '2016-12-01') & (crn['date'] <= '2019-12-01')
tcrn3 = crn[crn3]
tcrn3

             date product state  ...   route       tons        usd
90100  2016-12-01    corn    GO  ...  Ground     26.798    86177.0
90101  2016-12-01    corn    GO  ...     Sea    185.841   421879.0
90102  2016-12-01    corn    GO  ...     Sea    138.307   264785.0
90103  2016-12-01    corn    GO  ...     Sea    444.611    78475.0
90104  2016-12-01    corn    GO  ...     Sea   1124.148   174939.0
...           ...     ...   ...  ...     ...        ...        ...
117265 2019-12-01    corn    SP  ...     Sea   2575.793   402284.0
117266 2019-12-01    corn    TO  ...     Sea  27908.815  4433950.0
117267 2019-12-01    corn    TO  ...     Sea   1293.930   229003.0
117268 2019-12-01    corn    TO  ...     Air      0.007       27.0
117269 2019-12-01    corn    TO  ...     Sea   1874.085   283988.0

[4885 rows x 8 columns]

In [44]:
bpcorn = tcrn3.groupby(by='country')['usd'].sum()
bpcorn

country
Afghanistan            2.378200e+06
Algeria                2.650813e+08
Angola                 7.035458e+06
Argentina              1.884183e+07
Armenia                1.810070e+05
                           ...
Venezuela              4.735045e+07
Vietnam                1.581920e+09
Virgin Islands (UK)    3.737930e+05
Yemen                  3.412190e+05
Zambia                 4.070000e+02
Name: usd, Length: 113, dtype: float64

In [45]:
bp = pd.DataFrame(bpcorn)
bp.reset_index(inplace=True)
bp.columns = ['País', 'Total em exportações de milho (USD)']
bp

                    País  Total em exportações de milho (USD)
0            Afghanistan                         2.378200e+06
1                Algeria                         2.650813e+08
2                 Angola                         7.035458e+06
3              Argentina                         1.884183e+07
4                Armenia                         1.810070e+05
..                   ...                                  ...
108            Venezuela                         4.735045e+07
109              Vietnam                         1.581920e+09
110  Virgin Islands (UK)                         3.737930e+05
111                Yemen                         3.412190e+05
112               Zambia                         4.070000e+02

[113 rows x 2 columns]

In [46]:
bp.sort_values(by='Total em exportações de milho (USD)')

               País  Total em exportações de milho (USD)
17   Cayman Islands                         1.100000e+01
48      Isle of Man                         1.400000e+01
7           Bahrein                         1.500000e+01
75           Norway                         5.600000e+01
6           Bahamas                         7.500000e+01
..              ...                                  ...
92            Spain                         1.335770e+09
30            Egypt                         1.382825e+09
109         Vietnam                         1.581920e+09
52            Japan                         1.587077e+09
45             Iran                         2.885909e+09

[113 rows x 2 columns]

In [47]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["Espanha", "Egito", "Vietnam", "Japão", "Irã"],
    y=[1.336 , 1.383 , 1.582 , 1.587 , 2.886 ]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=750,
    yaxis=dict(
        title_text="Principais importadores de milho brasileiro nos últimos 3 anos (USD billions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

Pelo gráfico acima (valores aproximados em bilhões de dólares americanos) é possível constatar que os maiores parceiros comerciais na compra de milho brasileiro nos últimos 3 anos são: **Irã, Japão, Vietnã, Egito e Espanha**.

In [48]:
sgr3 = (sgr['date'] >= '2016-12-01') & (sgr['date'] <= '2019-12-01')
tsgr3 = sgr[sgr3]
tsgr3

             date product state  ...   route       tons         usd
90356  2016-12-01   sugar    AL  ...     Sea    405.000    204237.0
90357  2016-12-01   sugar    AL  ...     Sea  40000.000  16628300.0
90358  2016-12-01   sugar    AL  ...     Sea    270.000    147555.0
90359  2016-12-01   sugar    AL  ...     Sea  33057.327  15176556.0
90360  2016-12-01   sugar    AL  ...     Sea    540.000    295110.0
...           ...     ...   ...  ...     ...        ...         ...
117919 2019-12-01   sugar    SP  ...  Ground   1890.000    577618.0
117920 2019-12-01   sugar    SP  ...  Ground     80.000     55491.0
117921 2019-12-01   sugar    SP  ...     Sea   8967.646   3828624.0
117922 2019-12-01   sugar    SP  ...     Sea   5805.000   1726058.0
117923 2019-12-01   sugar    SP  ...     Sea  21422.839   6066211.0

[9050 rows x 8 columns]

In [49]:
bpsgr = tsgr3.groupby(by='country')['usd'].sum()
bpsgr

country
Afghanistan        9.718000e+03
Albania            8.548459e+06
Algeria            2.273125e+09
Americana Samoa    1.227290e+05
Angola             4.470969e+08
                       ...
Uruguay            7.836672e+07
Uzbekistan         3.906904e+07
Venezuela          2.888573e+08
Vietnam            4.175443e+06
Yemen              6.068181e+08
Name: usd, Length: 154, dtype: float64

In [50]:
bps = pd.DataFrame(bpsgr)
bps.reset_index(inplace=True)
bps.columns = ['País', 'Total em exportações de açúcar (USD)']
bps

                País  Total em exportações de açúcar (USD)
0        Afghanistan                          9.718000e+03
1            Albania                          8.548459e+06
2            Algeria                          2.273125e+09
3    Americana Samoa                          1.227290e+05
4             Angola                          4.470969e+08
..               ...                                   ...
149          Uruguay                          7.836672e+07
150       Uzbekistan                          3.906904e+07
151        Venezuela                          2.888573e+08
152          Vietnam                          4.175443e+06
153            Yemen                          6.068181e+08

[154 rows x 2 columns]

In [51]:
bps.sort_values(by='Total em exportações de açúcar (USD)')

                                País  Total em exportações de açúcar (USD)
21                            Brazil                          1.500000e+01
16                            Belize                          2.200000e+01
79                            Latvia                          2.600000e+01
20            Bosnia and Herzegovina                          4.000000e+01
117  Saint Vicent and the Granadines                          4.600000e+01
..                               ...                                   ...
119                     Saudi Arabia                          1.421949e+09
146             United Arab Emirates                          1.625861e+09
67                             India                          1.778902e+09
12                        Bangladesh                          2.140768e+09
2                            Algeria                          2.273125e+09

[154 rows x 2 columns]

In [52]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["Arábia Saudita", "Emirados Árabes Unidos", "India", "Bangladesh", "Argélia"],
    y=[1.422 , 1.626 , 1.779 , 2.141 , 2.273 ]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=750,
    yaxis=dict(
        title_text="Principais importadores de açúcar brasileiro nos últimos 3 anos (USD billions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

Analisando o gráfico acima (valores aproximados em bilhões de dólares americanos) percebe-se que os maiores parceiros comercias na compra do açúcar brasileiro nos últimos 3 anos são: **Argélia, Bangladesh, India, Emirados Árabes Unidos e Arábia Saudita**.

**Questão 05**

In [53]:
vcorn = crn.groupby(by='state')['usd'].sum()
vcorn

state
AC    1.857114e+06
AL    1.800000e+01
AM    6.620000e+02
AP    2.498760e+05
BA    1.476464e+08
CE    2.571120e+05
DF    2.858223e+07
ES    9.535775e+06
GO    5.706991e+09
MA    4.173487e+08
MG    8.312315e+08
MS    3.405431e+09
MT    2.837552e+10
PA    1.414647e+08
PB    2.706920e+06
PE    3.050760e+05
PI    6.259253e+07
PR    9.160512e+09
RJ    3.701790e+05
RN    1.852000e+03
RO    2.401818e+08
RR    5.663380e+05
RS    1.209460e+09
SC    4.425020e+08
SP    1.511122e+09
TO    2.693619e+08
Name: usd, dtype: float64

In [54]:
tecr = pd.DataFrame(vcorn)
tecr.reset_index(inplace=True)
tecr.columns = ['Estado', 'Total em exportações de milho (USD)']
tecr

   Estado  Total em exportações de milho (USD)
0      AC                         1.857114e+06
1      AL                         1.800000e+01
2      AM                         6.620000e+02
3      AP                         2.498760e+05
4      BA                         1.476464e+08
5      CE                         2.571120e+05
6      DF                         2.858223e+07
7      ES                         9.535775e+06
8      GO                         5.706991e+09
9      MA                         4.173487e+08
10     MG                         8.312315e+08
11     MS                         3.405431e+09
12     MT                         2.837552e+10
13     PA                         1.414647e+08
14     PB                         2.706920e+06
15     PE                         3.050760e+05
16     PI                         6.259253e+07
17     PR                         9.160512e+09
18     RJ                         3.701790e+05
19     RN                         1.852000e+03
20     RO                         2.401818e+08
21     RR                         5.663380e+05
22     RS                         1.209460e+09
23     SC                         4.425020e+08
24     SP                         1.511122e+09
25     TO                         2.693619e+08

In [55]:
tecr.sort_values(by='Total em exportações de milho (USD)')

   Estado  Total em exportações de milho (USD)
1      AL                         1.800000e+01
2      AM                         6.620000e+02
19     RN                         1.852000e+03
3      AP                         2.498760e+05
5      CE                         2.571120e+05
15     PE                         3.050760e+05
18     RJ                         3.701790e+05
21     RR                         5.663380e+05
0      AC                         1.857114e+06
14     PB                         2.706920e+06
7      ES                         9.535775e+06
6      DF                         2.858223e+07
16     PI                         6.259253e+07
13     PA                         1.414647e+08
4      BA                         1.476464e+08
20     RO                         2.401818e+08
25     TO                         2.693619e+08
9      MA                         4.173487e+08
23     SC                         4.425020e+08
10     MG                         8.312315e+08
22     RS                         1.209460e+09
24     SP                         1.511122e+09
11     MS                         3.405431e+09
8      GO                         5.706991e+09
17     PR                         9.160512e+09
12     MT                         2.837552e+10

In [56]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["SP", "MS", "GO", "PR", "MT"],
    y=[1.511 , 3.405 , 5.707 , 9.161 , 28.375]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=750,
    yaxis=dict(
        title_text="Principais Estados em exportação de milho (USD billions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

No gráfico acima tem-se os principais estados exportadores de milho com o valor total aproximado de vendas (em bilhões de dólares americanos). Sendo o estado do Mato Grosso (MT) o maior exportador.

In [57]:
vsgr = sgr.groupby(by='state')['usd'].sum()
vsgr

state
AC    3.194220e+05
AL    4.826419e+09
AM    2.825308e+07
AP    9.046800e+04
BA    7.262174e+06
CE    1.461000e+04
DF    1.216590e+05
ES    1.365109e+08
GO    3.040882e+09
MA    1.582713e+06
MG    8.559401e+09
MS    3.219035e+09
MT    2.291185e+08
PA    2.215464e+06
PB    1.778879e+08
PE    2.733034e+09
PI    7.570000e+02
PR    8.270779e+09
RJ    1.322024e+08
RN    2.420276e+08
RO    5.848920e+05
RR    2.981672e+07
RS    2.820824e+07
SC    1.047466e+08
SE    8.585313e+07
SP    6.621186e+10
Name: usd, dtype: float64

In [58]:
tvsgr = pd.DataFrame(vsgr)
tvsgr.reset_index(inplace=True)
tvsgr.columns = ['Estado', 'Total em exportações de açúcar (USD)']
tvsgr

   Estado  Total em exportações de açúcar (USD)
0      AC                          3.194220e+05
1      AL                          4.826419e+09
2      AM                          2.825308e+07
3      AP                          9.046800e+04
4      BA                          7.262174e+06
5      CE                          1.461000e+04
6      DF                          1.216590e+05
7      ES                          1.365109e+08
8      GO                          3.040882e+09
9      MA                          1.582713e+06
10     MG                          8.559401e+09
11     MS                          3.219035e+09
12     MT                          2.291185e+08
13     PA                          2.215464e+06
14     PB                          1.778879e+08
15     PE                          2.733034e+09
16     PI                          7.570000e+02
17     PR                          8.270779e+09
18     RJ                          1.322024e+08
19     RN                          2.420276e+08
20     RO                          5.848920e+05
21     RR                          2.981672e+07
22     RS                          2.820824e+07
23     SC                          1.047466e+08
24     SE                          8.585313e+07
25     SP                          6.621186e+10

In [59]:
tvsgr.sort_values(by='Total em exportações de açúcar (USD)')

   Estado  Total em exportações de açúcar (USD)
16     PI                          7.570000e+02
5      CE                          1.461000e+04
3      AP                          9.046800e+04
6      DF                          1.216590e+05
0      AC                          3.194220e+05
20     RO                          5.848920e+05
9      MA                          1.582713e+06
13     PA                          2.215464e+06
4      BA                          7.262174e+06
22     RS                          2.820824e+07
2      AM                          2.825308e+07
21     RR                          2.981672e+07
24     SE                          8.585313e+07
23     SC                          1.047466e+08
18     RJ                          1.322024e+08
7      ES                          1.365109e+08
14     PB                          1.778879e+08
12     MT                          2.291185e+08
19     RN                          2.420276e+08
15     PE                          2.733034e+09
8      GO                          3.040882e+09
11     MS                          3.219035e+09
1      AL                          4.826419e+09
17     PR                          8.270779e+09
10     MG                          8.559401e+09
25     SP                          6.621186e+10

In [60]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["SP", "MS", "AL", "PR", "MG"],
    y=[66.211 , 3.219 , 4.826 , 8.271 , 8.560]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=750,
    yaxis=dict(
        title_text="Principais Estados em exportação de açúcar (USD billions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

No gráfico acima tem-se os principais estados exportadores de açúcar com o valor total aproximado de vendas (em bilhões de dólares americanos). Sendo o estado de São Paulo (SP) o maior exportador.

In [61]:
vwh = wh.groupby(by='state')['usd'].sum()
vwh

state
DF    5.900000e+01
ES    3.300000e+02
GO    1.634900e+04
MA    6.400000e+01
MG    3.960000e+04
MS    2.757330e+05
PR    1.839354e+08
RJ    3.124800e+04
RO    3.275000e+03
RS    1.555925e+09
SC    2.540009e+07
SP    2.267024e+06
Name: usd, dtype: float64

In [62]:
tvwh = pd.DataFrame(vwh)
tvwh.reset_index(inplace=True)
tvwh.columns = ['Estado', 'Total em exportações de trigo (USD)']
tvwh

   Estado  Total em exportações de trigo (USD)
0      DF                         5.900000e+01
1      ES                         3.300000e+02
2      GO                         1.634900e+04
3      MA                         6.400000e+01
4      MG                         3.960000e+04
5      MS                         2.757330e+05
6      PR                         1.839354e+08
7      RJ                         3.124800e+04
8      RO                         3.275000e+03
9      RS                         1.555925e+09
10     SC                         2.540009e+07
11     SP                         2.267024e+06

In [63]:
tvwh.sort_values(by='Total em exportações de trigo (USD)')

   Estado  Total em exportações de trigo (USD)
0      DF                         5.900000e+01
3      MA                         6.400000e+01
1      ES                         3.300000e+02
8      RO                         3.275000e+03
2      GO                         1.634900e+04
7      RJ                         3.124800e+04
4      MG                         3.960000e+04
5      MS                         2.757330e+05
11     SP                         2.267024e+06
10     SC                         2.540009e+07
6      PR                         1.839354e+08
9      RS                         1.555925e+09

In [64]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["SP", "MS", "SC", "PR", "RS"],
    y=[2.267 , 0.276 , 25.400 , 183.935 , 1555.925]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=800,
    yaxis=dict(
        title_text="Principais Estados em exportação de trigo (USD millions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

No gráfico acima tem-se os principais estados exportadores de trigo com o valor total aproximado de vendas (em milhões de dólares americanos). Sendo o estado do Rio Grande do Sul (RS) o maior exportador do país.

In [65]:
vsbeans = soybeans.groupby(by='state')['usd'].sum()
vsbeans

state
AC    5.882280e+05
AL    1.900398e+07
AM    3.509449e+07
AP    6.904886e+07
BA    1.157671e+10
DF    7.127357e+08
ES    7.659868e+07
GO    2.126883e+10
MA    9.009265e+09
MG    1.030445e+10
MS    1.328482e+10
MT    8.050678e+10
PA    3.297939e+09
PB    3.243920e+06
PE    1.809754e+07
PI    2.442139e+09
PR    4.848410e+10
RJ    2.702981e+06
RO    3.227401e+09
RR    1.372994e+08
RS    4.613673e+10
SC    6.153502e+09
SE    2.016300e+04
SP    1.277089e+10
TO    6.700989e+09
Name: usd, dtype: float64

In [66]:
tvbeans = pd.DataFrame(vsbeans)
tvbeans.reset_index(inplace=True)
tvbeans.columns = ['Estado', 'Total em exportações de graõs de soja (USD)']
tvbeans

   Estado  Total em exportações de graõs de soja (USD)
0      AC                                 5.882280e+05
1      AL                                 1.900398e+07
2      AM                                 3.509449e+07
3      AP                                 6.904886e+07
4      BA                                 1.157671e+10
5      DF                                 7.127357e+08
6      ES                                 7.659868e+07
7      GO                                 2.126883e+10
8      MA                                 9.009265e+09
9      MG                                 1.030445e+10
10     MS                                 1.328482e+10
11     MT                                 8.050678e+10
12     PA                                 3.297939e+09
13     PB                                 3.243920e+06
14     PE                                 1.809754e+07
15     PI                                 2.442139e+09
16     PR                                 4.848410e+10
17     RJ                                 2.702981e+06
18     RO                                 3.227401e+09
19     RR                                 1.372994e+08
20     RS                                 4.613673e+10
21     SC                                 6.153502e+09
22     SE                                 2.016300e+04
23     SP                                 1.277089e+10
24     TO                                 6.700989e+09

In [67]:
tvbeans.sort_values(by='Total em exportações de graõs de soja (USD)')

   Estado  Total em exportações de graõs de soja (USD)
22     SE                                 2.016300e+04
0      AC                                 5.882280e+05
17     RJ                                 2.702981e+06
13     PB                                 3.243920e+06
14     PE                                 1.809754e+07
1      AL                                 1.900398e+07
2      AM                                 3.509449e+07
3      AP                                 6.904886e+07
6      ES                                 7.659868e+07
19     RR                                 1.372994e+08
5      DF                                 7.127357e+08
15     PI                                 2.442139e+09
18     RO                                 3.227401e+09
12     PA                                 3.297939e+09
21     SC                                 6.153502e+09
24     TO                                 6.700989e+09
8      MA                                 9.009265e+09
9      MG                                 1.030445e+10
4      BA                                 1.157671e+10
23     SP                                 1.277089e+10
10     MS                                 1.328482e+10
7      GO                                 2.126883e+10
20     RS                                 4.613673e+10
16     PR                                 4.848410e+10
11     MT                                 8.050678e+10

In [68]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["MT", "MS", "GO", "PR", "RS"],
    y=[80.507 , 13.285 , 21.269 , 48.484 , 46.137]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=800,
    yaxis=dict(
        title_text="Principais Estados exportadores de grãos de soja (USD billions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

No gráfico acima tem-se os maiores exportadores de grãos de soja (valores aproximados em bilhões de dólares americanos). Sendo o estado do Mato Grosso (MT) o maior exportador.

In [69]:
vsoil = soyoil.groupby(by='state')['usd'].sum()
vsoil

state
AC    5.214380e+05
AL    5.765000e+03
AM    2.408881e+07
AP    9.960000e+02
BA    1.349072e+08
CE    4.580000e+02
DF    1.204000e+03
ES    1.827310e+05
GO    8.559207e+08
MA    5.154897e+06
MG    7.145615e+08
MS    6.664741e+08
MT    5.434514e+09
PA    1.761895e+06
PE    2.204500e+07
PI    2.034810e+07
PR    1.110910e+10
RJ    4.182566e+06
RO    4.272910e+06
RR    9.311339e+06
RS    6.281965e+09
SC    1.238811e+09
SP    5.551762e+08
TO    1.099690e+05
Name: usd, dtype: float64

In [70]:
tvsoil = pd.DataFrame(vsoil)
tvsoil.reset_index(inplace=True)
tvsoil.columns = ['Estado', 'Total em exportações de óleo de soja (USD)']
tvsoil

   Estado  Total em exportações de óleo de soja (USD)
0      AC                                5.214380e+05
1      AL                                5.765000e+03
2      AM                                2.408881e+07
3      AP                                9.960000e+02
4      BA                                1.349072e+08
5      CE                                4.580000e+02
6      DF                                1.204000e+03
7      ES                                1.827310e+05
8      GO                                8.559207e+08
9      MA                                5.154897e+06
10     MG                                7.145615e+08
11     MS                                6.664741e+08
12     MT                                5.434514e+09
13     PA                                1.761895e+06
14     PE                                2.204500e+07
15     PI                                2.034810e+07
16     PR                                1.110910e+10
17     RJ                                4.182566e+06
18     RO                                4.272910e+06
19     RR                                9.311339e+06
20     RS                                6.281965e+09
21     SC                                1.238811e+09
22     SP                                5.551762e+08
23     TO                                1.099690e+05

In [71]:
tvsoil.sort_values(by='Total em exportações de óleo de soja (USD)')

   Estado  Total em exportações de óleo de soja (USD)
5      CE                                4.580000e+02
3      AP                                9.960000e+02
6      DF                                1.204000e+03
1      AL                                5.765000e+03
23     TO                                1.099690e+05
7      ES                                1.827310e+05
0      AC                                5.214380e+05
13     PA                                1.761895e+06
17     RJ                                4.182566e+06
18     RO                                4.272910e+06
9      MA                                5.154897e+06
19     RR                                9.311339e+06
15     PI                                2.034810e+07
14     PE                                2.204500e+07
2      AM                                2.408881e+07
4      BA                                1.349072e+08
22     SP                                5.551762e+08
11     MS                                6.664741e+08
10     MG                                7.145615e+08
8      GO                                8.559207e+08
21     SC                                1.238811e+09
12     MT                                5.434514e+09
20     RS                                6.281965e+09
16     PR                                1.110910e+10

In [72]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["MT", "SC", "GO", "PR", "RS"],
    y=[5.435 , 1.239 , 0.856 , 11.109 , 6.282]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=800,
    yaxis=dict(
        title_text="Principais Estados exportadores de óleo de soja (USD billions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

Pelo gráfico acima tem-se os maiores exportadores de óleo de soja (valores aproximados em bilhões de dólares americanos). Sendo o estado do Paraná (PR) o maior exportador.

In [73]:
vsm = soymeal.groupby(by='state')['usd'].sum()
vsm

state
AC    6.782400e+06
AL    6.390813e+06
AM    2.425885e+06
BA    5.439266e+09
CE    3.900000e+01
ES    4.492474e+06
GO    9.421431e+09
MA    1.304950e+08
MG    2.035734e+09
MS    3.159903e+09
MT    2.799454e+10
PA    1.208897e+06
PE    4.098248e+06
PI    1.529406e+08
PR    2.464996e+10
RJ    1.027038e+07
RN    6.000000e+05
RO    8.796660e+05
RR    3.115817e+06
RS    1.500739e+10
SC    8.856032e+08
SP    4.273386e+09
TO    1.664532e+08
Name: usd, dtype: float64

In [74]:
tvsm = pd.DataFrame(vsm)
tvsm.reset_index(inplace=True)
tvsm.columns = ['Estado', 'Total em exportações de carne de soja (USD)']
tvsm

   Estado  Total em exportações de carne de soja (USD)
0      AC                                 6.782400e+06
1      AL                                 6.390813e+06
2      AM                                 2.425885e+06
3      BA                                 5.439266e+09
4      CE                                 3.900000e+01
5      ES                                 4.492474e+06
6      GO                                 9.421431e+09
7      MA                                 1.304950e+08
8      MG                                 2.035734e+09
9      MS                                 3.159903e+09
10     MT                                 2.799454e+10
11     PA                                 1.208897e+06
12     PE                                 4.098248e+06
13     PI                                 1.529406e+08
14     PR                                 2.464996e+10
15     RJ                                 1.027038e+07
16     RN                                 6.000000e+05
17     RO                                 8.796660e+05
18     RR                                 3.115817e+06
19     RS                                 1.500739e+10
20     SC                                 8.856032e+08
21     SP                                 4.273386e+09
22     TO                                 1.664532e+08

In [75]:
tvsm.sort_values(by='Total em exportações de carne de soja (USD)')

   Estado  Total em exportações de carne de soja (USD)
4      CE                                 3.900000e+01
16     RN                                 6.000000e+05
17     RO                                 8.796660e+05
11     PA                                 1.208897e+06
2      AM                                 2.425885e+06
18     RR                                 3.115817e+06
12     PE                                 4.098248e+06
5      ES                                 4.492474e+06
1      AL                                 6.390813e+06
0      AC                                 6.782400e+06
15     RJ                                 1.027038e+07
7      MA                                 1.304950e+08
13     PI                                 1.529406e+08
22     TO                                 1.664532e+08
20     SC                                 8.856032e+08
8      MG                                 2.035734e+09
9      MS                                 3.159903e+09
21     SP                                 4.273386e+09
3      BA                                 5.439266e+09
6      GO                                 9.421431e+09
19     RS                                 1.500739e+10
14     PR                                 2.464996e+10
10     MT                                 2.799454e+10

In [76]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=["MT", "BA", "GO", "PR", "RS"],
    y=[27.995 , 5.440 , 9.421 , 24.650 , 15.007]
))

fig.update_layout(
    autosize=False,
    width=750,
    height=800,
    yaxis=dict(
        title_text="Principais Estados exportadores de carne de soja (USD billions)",
        tickmode="array",
        titlefont=dict(size=20),
    )
)

fig.update_yaxes(automargin=True)

fig.show()

Pelo gráfico acima tem-se os maiores exportadores de carne de soja (valores aproximados em bilhões de dólares americanos). Sendo o estado do Mato Grosso (MT) o maior exportador.